name: CI deploy
on: 
  push:
    tags:
      - v*


jobs:
  deployHeroku:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6' # Version range or exact version of a Ruby version to use, using semvers version range syntax.
    
    - name: Install ruby
      run: gem install dpl
    
    - name: Deploy on heroku
      run: dpl --provider=heroku --app=${{ secrets.HerokuNameAPI}} --api-key=${{secrets.HerokuKeyAPI}}

